/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainContactRouteImport } from './routes/_main/contact'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as MainProjectsIndexRouteImport } from './routes/_main/projects/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'
import { Route as ApiStorageUploadRouteRouteImport } from './routes/api/storage/upload/route'
import { Route as ApiStorageCleanupRouteRouteImport } from './routes/api/storage/cleanup/route'
import { Route as ProtectedAdminTechnologiesIndexRouteImport } from './routes/_protected/admin/technologies/index'
import { Route as ProtectedAdminTagsIndexRouteImport } from './routes/_protected/admin/tags/index'
import { Route as ProtectedAdminProjectsIndexRouteImport } from './routes/_protected/admin/projects/index'
import { Route as ProtectedAdminExperienceIndexRouteImport } from './routes/_protected/admin/experience/index'
import { Route as ProtectedAdminTechnologiesCreateRouteImport } from './routes/_protected/admin/technologies/create'
import { Route as ProtectedAdminTechnologiesTechnologyIdIndexRouteImport } from './routes/_protected/admin/technologies/$technologyId/index'
import { Route as ProtectedAdminTechnologiesTechnologyIdEditRouteImport } from './routes/_protected/admin/technologies/$technologyId/edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactRoute = MainContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const MainProjectsIndexRoute = MainProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ApiStorageUploadRouteRoute = ApiStorageUploadRouteRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageCleanupRouteRoute = ApiStorageCleanupRouteRouteImport.update({
  id: '/api/storage/cleanup',
  path: '/api/storage/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminTechnologiesIndexRoute =
  ProtectedAdminTechnologiesIndexRouteImport.update({
    id: '/technologies/',
    path: '/technologies/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTagsIndexRoute = ProtectedAdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminProjectsIndexRoute =
  ProtectedAdminProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminExperienceIndexRoute =
  ProtectedAdminExperienceIndexRouteImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTechnologiesCreateRoute =
  ProtectedAdminTechnologiesCreateRouteImport.update({
    id: '/technologies/create',
    path: '/technologies/create',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTechnologiesTechnologyIdIndexRoute =
  ProtectedAdminTechnologiesTechnologyIdIndexRouteImport.update({
    id: '/technologies/$technologyId/',
    path: '/technologies/$technologyId/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTechnologiesTechnologyIdEditRoute =
  ProtectedAdminTechnologiesTechnologyIdEditRouteImport.update({
    id: '/technologies/$technologyId/edit',
    path: '/technologies/$technologyId/edit',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/contact': typeof MainContactRoute
  '/api/storage/cleanup': typeof ApiStorageCleanupRouteRoute
  '/api/storage/upload': typeof ApiStorageUploadRouteRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/': typeof MainProjectsIndexRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/admin/technologies/create': typeof ProtectedAdminTechnologiesCreateRoute
  '/admin/experience/': typeof ProtectedAdminExperienceIndexRoute
  '/admin/projects/': typeof ProtectedAdminProjectsIndexRoute
  '/admin/tags/': typeof ProtectedAdminTagsIndexRoute
  '/admin/technologies/': typeof ProtectedAdminTechnologiesIndexRoute
  '/admin/technologies/$technologyId/edit': typeof ProtectedAdminTechnologiesTechnologyIdEditRoute
  '/admin/technologies/$technologyId/': typeof ProtectedAdminTechnologiesTechnologyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/login': typeof AuthLoginRoute
  '/contact': typeof MainContactRoute
  '/api/storage/cleanup': typeof ApiStorageCleanupRouteRoute
  '/api/storage/upload': typeof ApiStorageUploadRouteRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects': typeof MainProjectsIndexRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/admin/technologies/create': typeof ProtectedAdminTechnologiesCreateRoute
  '/admin/experience': typeof ProtectedAdminExperienceIndexRoute
  '/admin/projects': typeof ProtectedAdminProjectsIndexRoute
  '/admin/tags': typeof ProtectedAdminTagsIndexRoute
  '/admin/technologies': typeof ProtectedAdminTechnologiesIndexRoute
  '/admin/technologies/$technologyId/edit': typeof ProtectedAdminTechnologiesTechnologyIdEditRoute
  '/admin/technologies/$technologyId': typeof ProtectedAdminTechnologiesTechnologyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_main/contact': typeof MainContactRoute
  '/_main/': typeof MainIndexRoute
  '/api/storage/cleanup': typeof ApiStorageCleanupRouteRoute
  '/api/storage/upload': typeof ApiStorageUploadRouteRoute
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_main/projects/': typeof MainProjectsIndexRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/admin/technologies/create': typeof ProtectedAdminTechnologiesCreateRoute
  '/_protected/admin/experience/': typeof ProtectedAdminExperienceIndexRoute
  '/_protected/admin/projects/': typeof ProtectedAdminProjectsIndexRoute
  '/_protected/admin/tags/': typeof ProtectedAdminTagsIndexRoute
  '/_protected/admin/technologies/': typeof ProtectedAdminTechnologiesIndexRoute
  '/_protected/admin/technologies/$technologyId/edit': typeof ProtectedAdminTechnologiesTechnologyIdEditRoute
  '/_protected/admin/technologies/$technologyId/': typeof ProtectedAdminTechnologiesTechnologyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/contact'
    | '/api/storage/cleanup'
    | '/api/storage/upload'
    | '/admin/dashboard'
    | '/api/auth/$'
    | '/projects/'
    | '/admin/'
    | '/admin/technologies/create'
    | '/admin/experience/'
    | '/admin/projects/'
    | '/admin/tags/'
    | '/admin/technologies/'
    | '/admin/technologies/$technologyId/edit'
    | '/admin/technologies/$technologyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contact'
    | '/api/storage/cleanup'
    | '/api/storage/upload'
    | '/admin/dashboard'
    | '/api/auth/$'
    | '/projects'
    | '/admin'
    | '/admin/technologies/create'
    | '/admin/experience'
    | '/admin/projects'
    | '/admin/tags'
    | '/admin/technologies'
    | '/admin/technologies/$technologyId/edit'
    | '/admin/technologies/$technologyId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_protected'
    | '/_protected/admin'
    | '/_auth/login'
    | '/_main/contact'
    | '/_main/'
    | '/api/storage/cleanup'
    | '/api/storage/upload'
    | '/_protected/admin/dashboard'
    | '/api/auth/$'
    | '/_main/projects/'
    | '/_protected/admin/'
    | '/_protected/admin/technologies/create'
    | '/_protected/admin/experience/'
    | '/_protected/admin/projects/'
    | '/_protected/admin/tags/'
    | '/_protected/admin/technologies/'
    | '/_protected/admin/technologies/$technologyId/edit'
    | '/_protected/admin/technologies/$technologyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiStorageCleanupRouteRoute: typeof ApiStorageCleanupRouteRoute
  ApiStorageUploadRouteRoute: typeof ApiStorageUploadRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_main/projects/': {
      id: '/_main/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof MainProjectsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/cleanup': {
      id: '/api/storage/cleanup'
      path: '/api/storage/cleanup'
      fullPath: '/api/storage/cleanup'
      preLoaderRoute: typeof ApiStorageCleanupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/technologies/': {
      id: '/_protected/admin/technologies/'
      path: '/technologies'
      fullPath: '/admin/technologies/'
      preLoaderRoute: typeof ProtectedAdminTechnologiesIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/tags/': {
      id: '/_protected/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof ProtectedAdminTagsIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/projects/': {
      id: '/_protected/admin/projects/'
      path: '/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof ProtectedAdminProjectsIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/experience/': {
      id: '/_protected/admin/experience/'
      path: '/experience'
      fullPath: '/admin/experience/'
      preLoaderRoute: typeof ProtectedAdminExperienceIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/technologies/create': {
      id: '/_protected/admin/technologies/create'
      path: '/technologies/create'
      fullPath: '/admin/technologies/create'
      preLoaderRoute: typeof ProtectedAdminTechnologiesCreateRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/technologies/$technologyId/': {
      id: '/_protected/admin/technologies/$technologyId/'
      path: '/technologies/$technologyId'
      fullPath: '/admin/technologies/$technologyId/'
      preLoaderRoute: typeof ProtectedAdminTechnologiesTechnologyIdIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/technologies/$technologyId/edit': {
      id: '/_protected/admin/technologies/$technologyId/edit'
      path: '/technologies/$technologyId/edit'
      fullPath: '/admin/technologies/$technologyId/edit'
      preLoaderRoute: typeof ProtectedAdminTechnologiesTechnologyIdEditRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainContactRoute: typeof MainContactRoute
  MainIndexRoute: typeof MainIndexRoute
  MainProjectsIndexRoute: typeof MainProjectsIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainContactRoute: MainContactRoute,
  MainIndexRoute: MainIndexRoute,
  MainProjectsIndexRoute: MainProjectsIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminTechnologiesCreateRoute: typeof ProtectedAdminTechnologiesCreateRoute
  ProtectedAdminExperienceIndexRoute: typeof ProtectedAdminExperienceIndexRoute
  ProtectedAdminProjectsIndexRoute: typeof ProtectedAdminProjectsIndexRoute
  ProtectedAdminTagsIndexRoute: typeof ProtectedAdminTagsIndexRoute
  ProtectedAdminTechnologiesIndexRoute: typeof ProtectedAdminTechnologiesIndexRoute
  ProtectedAdminTechnologiesTechnologyIdEditRoute: typeof ProtectedAdminTechnologiesTechnologyIdEditRoute
  ProtectedAdminTechnologiesTechnologyIdIndexRoute: typeof ProtectedAdminTechnologiesTechnologyIdIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminTechnologiesCreateRoute: ProtectedAdminTechnologiesCreateRoute,
  ProtectedAdminExperienceIndexRoute: ProtectedAdminExperienceIndexRoute,
  ProtectedAdminProjectsIndexRoute: ProtectedAdminProjectsIndexRoute,
  ProtectedAdminTagsIndexRoute: ProtectedAdminTagsIndexRoute,
  ProtectedAdminTechnologiesIndexRoute: ProtectedAdminTechnologiesIndexRoute,
  ProtectedAdminTechnologiesTechnologyIdEditRoute:
    ProtectedAdminTechnologiesTechnologyIdEditRoute,
  ProtectedAdminTechnologiesTechnologyIdIndexRoute:
    ProtectedAdminTechnologiesTechnologyIdIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiStorageCleanupRouteRoute: ApiStorageCleanupRouteRoute,
  ApiStorageUploadRouteRoute: ApiStorageUploadRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
