/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ApiHealthRouteRouteImport } from './routes/api/health/route'
import { Route as ProtectedAdminRouteRouteImport } from './routes/_protected/admin/route'
import { Route as MainContactRouteRouteImport } from './routes/_main/contact/route'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as MainProjectIndexRouteImport } from './routes/_main/project/index'
import { Route as MainContactIndexRouteImport } from './routes/_main/contact/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedAdminDashboardRouteImport } from './routes/_protected/admin/dashboard'
import { Route as MainProjectProjectIdRouteImport } from './routes/_main/project/$projectId'
import { Route as ApiStorageUploadRouteRouteImport } from './routes/api/storage/upload/route'
import { Route as ProtectedAdminTechnologyIndexRouteImport } from './routes/_protected/admin/technology/index'
import { Route as ProtectedAdminTagsIndexRouteImport } from './routes/_protected/admin/tags/index'
import { Route as ProtectedAdminProjectIndexRouteImport } from './routes/_protected/admin/project/index'
import { Route as ProtectedAdminExperienceIndexRouteImport } from './routes/_protected/admin/experience/index'
import { Route as ProtectedAdminContactMessageIndexRouteImport } from './routes/_protected/admin/contact-message/index'
import { Route as ProtectedAdminTechnologyCreateRouteImport } from './routes/_protected/admin/technology/create'
import { Route as ProtectedAdminProjectCreateRouteImport } from './routes/_protected/admin/project/create'
import { Route as ProtectedAdminExperienceCreateRouteImport } from './routes/_protected/admin/experience/create'
import { Route as ProtectedAdminTechnologyTechnologyIdIndexRouteImport } from './routes/_protected/admin/technology/$technologyId/index'
import { Route as ProtectedAdminProjectProjectIdIndexRouteImport } from './routes/_protected/admin/project/$projectId/index'
import { Route as ProtectedAdminContactMessageContactMessageIdIndexRouteImport } from './routes/_protected/admin/contact-message/$contactMessageId/index'
import { Route as ProtectedAdminTechnologyTechnologyIdEditRouteImport } from './routes/_protected/admin/technology/$technologyId/edit'
import { Route as ProtectedAdminProjectProjectIdEditRouteImport } from './routes/_protected/admin/project/$projectId/edit'
import { Route as ProtectedAdminExperienceExperienceIdEditRouteImport } from './routes/_protected/admin/experience/$experienceId/edit'

const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiHealthRouteRoute = ApiHealthRouteRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRouteRoute = ProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const MainContactRouteRoute = MainContactRouteRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => MainRouteRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const MainProjectIndexRoute = MainProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainContactIndexRoute = MainContactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainContactRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminDashboardRoute = ProtectedAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const MainProjectProjectIdRoute = MainProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => MainRouteRoute,
} as any)
const ApiStorageUploadRouteRoute = ApiStorageUploadRouteRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminTechnologyIndexRoute =
  ProtectedAdminTechnologyIndexRouteImport.update({
    id: '/technology/',
    path: '/technology/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTagsIndexRoute = ProtectedAdminTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => ProtectedAdminRouteRoute,
} as any)
const ProtectedAdminProjectIndexRoute =
  ProtectedAdminProjectIndexRouteImport.update({
    id: '/project/',
    path: '/project/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminExperienceIndexRoute =
  ProtectedAdminExperienceIndexRouteImport.update({
    id: '/experience/',
    path: '/experience/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminContactMessageIndexRoute =
  ProtectedAdminContactMessageIndexRouteImport.update({
    id: '/contact-message/',
    path: '/contact-message/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTechnologyCreateRoute =
  ProtectedAdminTechnologyCreateRouteImport.update({
    id: '/technology/create',
    path: '/technology/create',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminProjectCreateRoute =
  ProtectedAdminProjectCreateRouteImport.update({
    id: '/project/create',
    path: '/project/create',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminExperienceCreateRoute =
  ProtectedAdminExperienceCreateRouteImport.update({
    id: '/experience/create',
    path: '/experience/create',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTechnologyTechnologyIdIndexRoute =
  ProtectedAdminTechnologyTechnologyIdIndexRouteImport.update({
    id: '/technology/$technologyId/',
    path: '/technology/$technologyId/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminProjectProjectIdIndexRoute =
  ProtectedAdminProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminContactMessageContactMessageIdIndexRoute =
  ProtectedAdminContactMessageContactMessageIdIndexRouteImport.update({
    id: '/contact-message/$contactMessageId/',
    path: '/contact-message/$contactMessageId/',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminTechnologyTechnologyIdEditRoute =
  ProtectedAdminTechnologyTechnologyIdEditRouteImport.update({
    id: '/technology/$technologyId/edit',
    path: '/technology/$technologyId/edit',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminProjectProjectIdEditRoute =
  ProtectedAdminProjectProjectIdEditRouteImport.update({
    id: '/project/$projectId/edit',
    path: '/project/$projectId/edit',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)
const ProtectedAdminExperienceExperienceIdEditRoute =
  ProtectedAdminExperienceExperienceIdEditRouteImport.update({
    id: '/experience/$experienceId/edit',
    path: '/experience/$experienceId/edit',
    getParentRoute: () => ProtectedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/contact': typeof MainContactRouteRouteWithChildren
  '/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/api/health': typeof ApiHealthRouteRoute
  '/login': typeof AuthLoginRoute
  '/api/storage/upload': typeof ApiStorageUploadRouteRoute
  '/project/$projectId': typeof MainProjectProjectIdRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contact/': typeof MainContactIndexRoute
  '/project/': typeof MainProjectIndexRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/admin/experience/create': typeof ProtectedAdminExperienceCreateRoute
  '/admin/project/create': typeof ProtectedAdminProjectCreateRoute
  '/admin/technology/create': typeof ProtectedAdminTechnologyCreateRoute
  '/admin/contact-message/': typeof ProtectedAdminContactMessageIndexRoute
  '/admin/experience/': typeof ProtectedAdminExperienceIndexRoute
  '/admin/project/': typeof ProtectedAdminProjectIndexRoute
  '/admin/tags/': typeof ProtectedAdminTagsIndexRoute
  '/admin/technology/': typeof ProtectedAdminTechnologyIndexRoute
  '/admin/experience/$experienceId/edit': typeof ProtectedAdminExperienceExperienceIdEditRoute
  '/admin/project/$projectId/edit': typeof ProtectedAdminProjectProjectIdEditRoute
  '/admin/technology/$technologyId/edit': typeof ProtectedAdminTechnologyTechnologyIdEditRoute
  '/admin/contact-message/$contactMessageId/': typeof ProtectedAdminContactMessageContactMessageIdIndexRoute
  '/admin/project/$projectId/': typeof ProtectedAdminProjectProjectIdIndexRoute
  '/admin/technology/$technologyId/': typeof ProtectedAdminTechnologyTechnologyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/api/health': typeof ApiHealthRouteRoute
  '/login': typeof AuthLoginRoute
  '/api/storage/upload': typeof ApiStorageUploadRouteRoute
  '/project/$projectId': typeof MainProjectProjectIdRoute
  '/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/contact': typeof MainContactIndexRoute
  '/project': typeof MainProjectIndexRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/admin/experience/create': typeof ProtectedAdminExperienceCreateRoute
  '/admin/project/create': typeof ProtectedAdminProjectCreateRoute
  '/admin/technology/create': typeof ProtectedAdminTechnologyCreateRoute
  '/admin/contact-message': typeof ProtectedAdminContactMessageIndexRoute
  '/admin/experience': typeof ProtectedAdminExperienceIndexRoute
  '/admin/project': typeof ProtectedAdminProjectIndexRoute
  '/admin/tags': typeof ProtectedAdminTagsIndexRoute
  '/admin/technology': typeof ProtectedAdminTechnologyIndexRoute
  '/admin/experience/$experienceId/edit': typeof ProtectedAdminExperienceExperienceIdEditRoute
  '/admin/project/$projectId/edit': typeof ProtectedAdminProjectProjectIdEditRoute
  '/admin/technology/$technologyId/edit': typeof ProtectedAdminTechnologyTechnologyIdEditRoute
  '/admin/contact-message/$contactMessageId': typeof ProtectedAdminContactMessageContactMessageIdIndexRoute
  '/admin/project/$projectId': typeof ProtectedAdminProjectProjectIdIndexRoute
  '/admin/technology/$technologyId': typeof ProtectedAdminTechnologyTechnologyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/_main/contact': typeof MainContactRouteRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteRouteWithChildren
  '/api/health': typeof ApiHealthRouteRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_main/': typeof MainIndexRoute
  '/api/storage/upload': typeof ApiStorageUploadRouteRoute
  '/_main/project/$projectId': typeof MainProjectProjectIdRoute
  '/_protected/admin/dashboard': typeof ProtectedAdminDashboardRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_main/contact/': typeof MainContactIndexRoute
  '/_main/project/': typeof MainProjectIndexRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/admin/experience/create': typeof ProtectedAdminExperienceCreateRoute
  '/_protected/admin/project/create': typeof ProtectedAdminProjectCreateRoute
  '/_protected/admin/technology/create': typeof ProtectedAdminTechnologyCreateRoute
  '/_protected/admin/contact-message/': typeof ProtectedAdminContactMessageIndexRoute
  '/_protected/admin/experience/': typeof ProtectedAdminExperienceIndexRoute
  '/_protected/admin/project/': typeof ProtectedAdminProjectIndexRoute
  '/_protected/admin/tags/': typeof ProtectedAdminTagsIndexRoute
  '/_protected/admin/technology/': typeof ProtectedAdminTechnologyIndexRoute
  '/_protected/admin/experience/$experienceId/edit': typeof ProtectedAdminExperienceExperienceIdEditRoute
  '/_protected/admin/project/$projectId/edit': typeof ProtectedAdminProjectProjectIdEditRoute
  '/_protected/admin/technology/$technologyId/edit': typeof ProtectedAdminTechnologyTechnologyIdEditRoute
  '/_protected/admin/contact-message/$contactMessageId/': typeof ProtectedAdminContactMessageContactMessageIdIndexRoute
  '/_protected/admin/project/$projectId/': typeof ProtectedAdminProjectProjectIdIndexRoute
  '/_protected/admin/technology/$technologyId/': typeof ProtectedAdminTechnologyTechnologyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/contact'
    | '/admin'
    | '/api/health'
    | '/login'
    | '/api/storage/upload'
    | '/project/$projectId'
    | '/admin/dashboard'
    | '/api/auth/$'
    | '/contact/'
    | '/project/'
    | '/admin/'
    | '/admin/experience/create'
    | '/admin/project/create'
    | '/admin/technology/create'
    | '/admin/contact-message/'
    | '/admin/experience/'
    | '/admin/project/'
    | '/admin/tags/'
    | '/admin/technology/'
    | '/admin/experience/$experienceId/edit'
    | '/admin/project/$projectId/edit'
    | '/admin/technology/$technologyId/edit'
    | '/admin/contact-message/$contactMessageId/'
    | '/admin/project/$projectId/'
    | '/admin/technology/$technologyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/api/health'
    | '/login'
    | '/api/storage/upload'
    | '/project/$projectId'
    | '/admin/dashboard'
    | '/api/auth/$'
    | '/contact'
    | '/project'
    | '/admin'
    | '/admin/experience/create'
    | '/admin/project/create'
    | '/admin/technology/create'
    | '/admin/contact-message'
    | '/admin/experience'
    | '/admin/project'
    | '/admin/tags'
    | '/admin/technology'
    | '/admin/experience/$experienceId/edit'
    | '/admin/project/$projectId/edit'
    | '/admin/technology/$technologyId/edit'
    | '/admin/contact-message/$contactMessageId'
    | '/admin/project/$projectId'
    | '/admin/technology/$technologyId'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_protected'
    | '/robots.txt'
    | '/_main/contact'
    | '/_protected/admin'
    | '/api/health'
    | '/_auth/login'
    | '/_main/'
    | '/api/storage/upload'
    | '/_main/project/$projectId'
    | '/_protected/admin/dashboard'
    | '/api/auth/$'
    | '/_main/contact/'
    | '/_main/project/'
    | '/_protected/admin/'
    | '/_protected/admin/experience/create'
    | '/_protected/admin/project/create'
    | '/_protected/admin/technology/create'
    | '/_protected/admin/contact-message/'
    | '/_protected/admin/experience/'
    | '/_protected/admin/project/'
    | '/_protected/admin/tags/'
    | '/_protected/admin/technology/'
    | '/_protected/admin/experience/$experienceId/edit'
    | '/_protected/admin/project/$projectId/edit'
    | '/_protected/admin/technology/$technologyId/edit'
    | '/_protected/admin/contact-message/$contactMessageId/'
    | '/_protected/admin/project/$projectId/'
    | '/_protected/admin/technology/$technologyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ApiHealthRouteRoute: typeof ApiHealthRouteRoute
  ApiStorageUploadRouteRoute: typeof ApiStorageUploadRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_main/contact': {
      id: '/_main/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MainContactRouteRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_main/project/': {
      id: '/_main/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof MainProjectIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/contact/': {
      id: '/_main/contact/'
      path: '/'
      fullPath: '/contact/'
      preLoaderRoute: typeof MainContactIndexRouteImport
      parentRoute: typeof MainContactRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/dashboard': {
      id: '/_protected/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof ProtectedAdminDashboardRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_main/project/$projectId': {
      id: '/_main/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof MainProjectProjectIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/technology/': {
      id: '/_protected/admin/technology/'
      path: '/technology'
      fullPath: '/admin/technology/'
      preLoaderRoute: typeof ProtectedAdminTechnologyIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/tags/': {
      id: '/_protected/admin/tags/'
      path: '/tags'
      fullPath: '/admin/tags/'
      preLoaderRoute: typeof ProtectedAdminTagsIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/project/': {
      id: '/_protected/admin/project/'
      path: '/project'
      fullPath: '/admin/project/'
      preLoaderRoute: typeof ProtectedAdminProjectIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/experience/': {
      id: '/_protected/admin/experience/'
      path: '/experience'
      fullPath: '/admin/experience/'
      preLoaderRoute: typeof ProtectedAdminExperienceIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/contact-message/': {
      id: '/_protected/admin/contact-message/'
      path: '/contact-message'
      fullPath: '/admin/contact-message/'
      preLoaderRoute: typeof ProtectedAdminContactMessageIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/technology/create': {
      id: '/_protected/admin/technology/create'
      path: '/technology/create'
      fullPath: '/admin/technology/create'
      preLoaderRoute: typeof ProtectedAdminTechnologyCreateRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/project/create': {
      id: '/_protected/admin/project/create'
      path: '/project/create'
      fullPath: '/admin/project/create'
      preLoaderRoute: typeof ProtectedAdminProjectCreateRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/experience/create': {
      id: '/_protected/admin/experience/create'
      path: '/experience/create'
      fullPath: '/admin/experience/create'
      preLoaderRoute: typeof ProtectedAdminExperienceCreateRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/technology/$technologyId/': {
      id: '/_protected/admin/technology/$technologyId/'
      path: '/technology/$technologyId'
      fullPath: '/admin/technology/$technologyId/'
      preLoaderRoute: typeof ProtectedAdminTechnologyTechnologyIdIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/project/$projectId/': {
      id: '/_protected/admin/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/admin/project/$projectId/'
      preLoaderRoute: typeof ProtectedAdminProjectProjectIdIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/contact-message/$contactMessageId/': {
      id: '/_protected/admin/contact-message/$contactMessageId/'
      path: '/contact-message/$contactMessageId'
      fullPath: '/admin/contact-message/$contactMessageId/'
      preLoaderRoute: typeof ProtectedAdminContactMessageContactMessageIdIndexRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/technology/$technologyId/edit': {
      id: '/_protected/admin/technology/$technologyId/edit'
      path: '/technology/$technologyId/edit'
      fullPath: '/admin/technology/$technologyId/edit'
      preLoaderRoute: typeof ProtectedAdminTechnologyTechnologyIdEditRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/project/$projectId/edit': {
      id: '/_protected/admin/project/$projectId/edit'
      path: '/project/$projectId/edit'
      fullPath: '/admin/project/$projectId/edit'
      preLoaderRoute: typeof ProtectedAdminProjectProjectIdEditRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
    '/_protected/admin/experience/$experienceId/edit': {
      id: '/_protected/admin/experience/$experienceId/edit'
      path: '/experience/$experienceId/edit'
      fullPath: '/admin/experience/$experienceId/edit'
      preLoaderRoute: typeof ProtectedAdminExperienceExperienceIdEditRouteImport
      parentRoute: typeof ProtectedAdminRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainContactRouteRouteChildren {
  MainContactIndexRoute: typeof MainContactIndexRoute
}

const MainContactRouteRouteChildren: MainContactRouteRouteChildren = {
  MainContactIndexRoute: MainContactIndexRoute,
}

const MainContactRouteRouteWithChildren =
  MainContactRouteRoute._addFileChildren(MainContactRouteRouteChildren)

interface MainRouteRouteChildren {
  MainContactRouteRoute: typeof MainContactRouteRouteWithChildren
  MainIndexRoute: typeof MainIndexRoute
  MainProjectProjectIdRoute: typeof MainProjectProjectIdRoute
  MainProjectIndexRoute: typeof MainProjectIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainContactRouteRoute: MainContactRouteRouteWithChildren,
  MainIndexRoute: MainIndexRoute,
  MainProjectProjectIdRoute: MainProjectProjectIdRoute,
  MainProjectIndexRoute: MainProjectIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

interface ProtectedAdminRouteRouteChildren {
  ProtectedAdminDashboardRoute: typeof ProtectedAdminDashboardRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
  ProtectedAdminExperienceCreateRoute: typeof ProtectedAdminExperienceCreateRoute
  ProtectedAdminProjectCreateRoute: typeof ProtectedAdminProjectCreateRoute
  ProtectedAdminTechnologyCreateRoute: typeof ProtectedAdminTechnologyCreateRoute
  ProtectedAdminContactMessageIndexRoute: typeof ProtectedAdminContactMessageIndexRoute
  ProtectedAdminExperienceIndexRoute: typeof ProtectedAdminExperienceIndexRoute
  ProtectedAdminProjectIndexRoute: typeof ProtectedAdminProjectIndexRoute
  ProtectedAdminTagsIndexRoute: typeof ProtectedAdminTagsIndexRoute
  ProtectedAdminTechnologyIndexRoute: typeof ProtectedAdminTechnologyIndexRoute
  ProtectedAdminExperienceExperienceIdEditRoute: typeof ProtectedAdminExperienceExperienceIdEditRoute
  ProtectedAdminProjectProjectIdEditRoute: typeof ProtectedAdminProjectProjectIdEditRoute
  ProtectedAdminTechnologyTechnologyIdEditRoute: typeof ProtectedAdminTechnologyTechnologyIdEditRoute
  ProtectedAdminContactMessageContactMessageIdIndexRoute: typeof ProtectedAdminContactMessageContactMessageIdIndexRoute
  ProtectedAdminProjectProjectIdIndexRoute: typeof ProtectedAdminProjectProjectIdIndexRoute
  ProtectedAdminTechnologyTechnologyIdIndexRoute: typeof ProtectedAdminTechnologyTechnologyIdIndexRoute
}

const ProtectedAdminRouteRouteChildren: ProtectedAdminRouteRouteChildren = {
  ProtectedAdminDashboardRoute: ProtectedAdminDashboardRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
  ProtectedAdminExperienceCreateRoute: ProtectedAdminExperienceCreateRoute,
  ProtectedAdminProjectCreateRoute: ProtectedAdminProjectCreateRoute,
  ProtectedAdminTechnologyCreateRoute: ProtectedAdminTechnologyCreateRoute,
  ProtectedAdminContactMessageIndexRoute:
    ProtectedAdminContactMessageIndexRoute,
  ProtectedAdminExperienceIndexRoute: ProtectedAdminExperienceIndexRoute,
  ProtectedAdminProjectIndexRoute: ProtectedAdminProjectIndexRoute,
  ProtectedAdminTagsIndexRoute: ProtectedAdminTagsIndexRoute,
  ProtectedAdminTechnologyIndexRoute: ProtectedAdminTechnologyIndexRoute,
  ProtectedAdminExperienceExperienceIdEditRoute:
    ProtectedAdminExperienceExperienceIdEditRoute,
  ProtectedAdminProjectProjectIdEditRoute:
    ProtectedAdminProjectProjectIdEditRoute,
  ProtectedAdminTechnologyTechnologyIdEditRoute:
    ProtectedAdminTechnologyTechnologyIdEditRoute,
  ProtectedAdminContactMessageContactMessageIdIndexRoute:
    ProtectedAdminContactMessageContactMessageIdIndexRoute,
  ProtectedAdminProjectProjectIdIndexRoute:
    ProtectedAdminProjectProjectIdIndexRoute,
  ProtectedAdminTechnologyTechnologyIdIndexRoute:
    ProtectedAdminTechnologyTechnologyIdIndexRoute,
}

const ProtectedAdminRouteRouteWithChildren =
  ProtectedAdminRouteRoute._addFileChildren(ProtectedAdminRouteRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRouteRoute: typeof ProtectedAdminRouteRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRouteRoute: ProtectedAdminRouteRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ApiHealthRouteRoute: ApiHealthRouteRoute,
  ApiStorageUploadRouteRoute: ApiStorageUploadRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
